package com.example.dota2project.UI

class Utils() {

    val PSGDescription = "LGD's first step into DotA was the sponsorship of the squad known as For The Dream, which won SMM 2009. The organization has been a powerhouse of the Chinese scene ever since. The team began its transition into Dota 2 in 2012, which was revealed on March 19th.[1] Shortly after The International 2012, in which the team placed third, LGD announced a second squad on October 15th, made up of international players, which would play under the tag LGD.int.[2] LGD.int would end up disbanding in December 2013, after continuous roster troubles late that year. In April 2014, LGD signed a new squad, LGD.CDEC (Chinese Dota Elite Community), made up of newcomers to the scene, and captained by recent LGD player Maybe. In October 2014, LGD.CDEC was re-branded as CDEC Gaming for better exposure. On April 19th 2018, LGD entered a partnership with French football giants Paris Saint-Germain. The main squad would be known as PSG.LGD."
    val ViciDescription = "Vici Gaming was formed on October 21st, 2012[1] with the help of “Fengdidi”, who also had previously played in PanDarea Gaming under the name “PanPan”, handpicking highly skilled players that were highly ranked on the Chinese DotA ladder at the time.\n" +
            "\n" +
            "The players had no previous professional experience at the time with the exception of sydm who had played under the banner of TyLoo. Notably, their mid lane player “Cty” had shown promise by winning a 1v1 tournament organized by 2009, in which he beat famous players like Ferrari_430, Sylar, Hao, and other top Chinese players shortly before getting recruited.\n" +
            "\n" +
            "The team qualified for the 2012 G-League Season 2 by beating Noah's Ark in the preliminaries.\n" +
            "\n" +
            "On January 28th, Vici signed the team Greedy, captained by the famous YaphetS as their online/backup squad. The rest of the team consisted of xiaotuji, Maybe, nL_Ks, and Q. They were focused on the original DotA, although they have since expanded to Dota 2.[2]\n" +
            "\n" +
            "On March 1st, Vici signed ZSMJ, who built a Dota 2 squad.[3] It was believed that ZSMJ brought some of his teammates from his project with Chisbug with him to Vici Gaming, of which one is definitely Sgua_Li. In the following weeks, Vici Gaming made roster adjustments, dropping some players in private while sending out a public notice for interested players to contact them.[4]\n" +
            "\n" +
            "On March 28th, It was announced that carry player ZSMJ replaced mid player sydm and that former carry Cty picked up the mid role.[5]\n" +
            "\n" +
            "In June 2013, following elimination from the The International 2013 qualifiers and a disappointing finish outside playoff places in DSL, Vici Gaming announced the departure of team executive, PandaPanPan, and team manager, Nada. Their replacement was mikasa, who occasionally played as a substitute for VG.\n" +
            "\n" +
            "In December 2013, Vici Gaming traveled to Poland to compete in the Raidcall EMS Fall LAN finals, joining the ranks of teams like Alliance, Navi and DK who were pioneers in east-west tournament participation.[6] Following this, the team also traveled to the Kingston HyperX Dota 2 League offline finals in Las Vegas in 2014.[7] Vici would go on to take first place at EMS One Fall, but would subsequently fall from the top of Dota 2 due to a lack of direction and poor player performances. Despite placing at many events Vici would not achieve another title in the TI3 to TI4 season.\n" +
            "\n" +
            "At the end of April 2014 Vici Gaming was awarded a direct invite to The International 4,[8] where they would go on to place first in the group stage and second overall.\n" +
            "\n" +
            "After The International 4, Vici Gaming made big chances to their roster by acquiring Black and iceiceice in the carry and offlane positions, respectively. After these transfers, the team managed to place first in many premier tournaments such as i-League, ESL One New York 2014 and The Summit 2. In February 2015, Vici Gaming was invited to the Dota 2 Asia Championships which had the largest prize pool outside of The International events. Vici Gaming finished as a runner-up in the tournament, knocking out the tournament favorites Team Secret but were swept by Evil Geniuses in the grand finals.\n" +
            "\n" +
            "In the post-DAC shuffle in March 2015, Vici Gaming made a new youth squad called Vici Gaming Potential (abbreviated as VG.P) which consisted of promising new players in the Chinese Dota scene. Changes were also made in the main team with the replacement of Black with Hao. After the shuffle, Vici Gaming continued to show strong results in premier tournaments by placing 1st in Star Ladder Star Series Season 12 and runners-up in i-League Season 3. Because of these strong results, Vici Gaming were awarded a direct invite to The International 5 where despite having a rough group stage and being placed in the lower bracket, managed to finish 4th in the tournament."

    val EGDescription = "In October 2011, following The International 2011, Evil Geniuses announced the formation of their new Dota 2 division, including the return of two former DotA players, Jimmy \"DeMoN\" Ho and Clinton \"Fear\" Loomis. Their first roster consisted of Amel \"PlaymatE\" Barudzija, Jimmy \"DeMoN\" Ho, Rasmus \"MiSeRy\" Berth Filipsen, Clinton \"Fear\" Loomis and Per-Anders \"Pajkatt\" Olsson Lille. The team's first job was travelling to China to bootcamp for the future tournaments they would participate in the region including SMM 2011 and G-League Season 3. They managed to get to the quarter finals in the second edition of the World DotA Championship and then proceeded to play SMM 2011. However, due to issues with renewing his visa, PlaymatE had to depart early and was temporarily replaced with Chinese player Luo before the tournament began. Picking a unique strategy, the team was able to gain a convincing lead against MiTH.Trust in the upper bracket of the tournament, when suddenly a player of the MiTH squad crashed. This forced a replay of the entire match due to a controversial ruling which stated that the system which determined who was leading in the case of a crash or technical issue was only applicable after a certain amount of in game time had passed. Because of this and other problems regarding the organization of the tournament, EG decided to boycott the tournament.[1] In G-League Season 3 they failed to make it past the group stage. After the players returned home and a subsequent brief break, they shifted their focus fully to Dota 2, with a mindset of quickly reaching the highest levels of competition."
    val VPDescription = "The organization has been represented by more than 50 players. Since 2003 they have won more than 100 gold, 170 silver and 220 bronze medals in more than 10 esports disciplines.[needs update]\n" +
            "\n" +
            "A women's team was established on September 5, 2012.[1]\n" +
            "\n" +
            "Virtus.pro Polar was formed on September 18, 2014[2] by NVMI players. It was later rebranded to ASUS.Polar as an attempt to create a separate brand under a single ownership, but it didn't turn out to be a success, and the team was merged with the main Virtus.pro roster and ceased to exist as a brand.[3]\n" +
            "\n" +
            "On May 30th 2016, after accusations that the team had used No[o]ne as a standin for ALOHADANCE in The Summit 5 Qualifiers Finals vs Ad Finem, using ALOHADANCE's account to hide the action, Virtus.pro admitted that they had broken the rules, and were removed from the tournament.[4]\n" +
            "\n" +
            "The entire Dota 2 squad was dropped by the organization on 30 June 2016,[5] after increasingly poor results culminated in a disappointing 6th-place finish in the Qualifiers for The International 2016, thus failing to qualify for yet another event. Following the International, Virtus pro later revamped their Dota 2 squad and won The Summit 6.[6]\n" +
            "\n" +
            "Sustained success followed, and from 2017 to 2018 the team won a total of five majors, though success at The International remained elusive. In late 2020, a new roster consisting of the VP.Prodigy squad was signed, leading to impressive results in the Dota Pro Circuit regional leagues in 2021. Virtus Pro were the only team in any region to finish 7-0 in both of their first two seasons."
    val IGDescription = "Invictus Gaming was created in August 2011 with the purchase of Catastrophic Cruel Memory, the strongest team in the scene at the time. The newly re-branded iG was seen as the new flagship of Chinese DotA. The creation of iG.Y after poaching 4 of the members of LGD, historically one of the strongest teams in China, came as a shock just days after the purchase of CCM, now dubbed iG.Z. Having moved into the DotA scene with what seemed to be overwhelming force, the two iG teams represented what appeared to be the two strongest teams in the scene. The prophesied domination, however, never came, iG (CCM) lost in an upset to the up-and-coming Tyloo in the Chinese WCG 2011 Finals and no longer seemed invincible to top-level teams. Soon thereafter iG (CCM) lost Xiao8 and DDC to LGD as they left to reform a new LGD with ZSMJ, its previous captain and the only player who did not transfer to iG. After purchasing Awoke and Faith from Tyloo for iG(CCM) and CH from Panda to complete the previous LGD squad, iG reformed into iG.Z (Zhou) out of the previous CCM and iG.Y (YYF) out of the previous LGD. Weakened by the constant reorganization, both iGs would suffer at the hands of a resurgent DK and was defeated in both WDC 2011 and G-League 2011. It also performed poorly at the International 2011, with its unprepared players of iG.Z ending up so demoralized as to forfeit its final placement matches after being eliminated from the tournament and the iG.Y section unable to compete due to ZSMJ's refusal to temporarily play with his previous teammates under the LGD banner. Hampered by constant disappointing performances, iG eventually reformed its squad into a single collection of some of the best talents the Chinese DotA scene had to offer in the form of Zhou, 430, YYF, Chuan, and Faith. This new team, despite being hampered by a lack of team coordination and synergy resulting from the combination of 4 players who had all previously required large amounts of farm, nevertheless was able to win SMM 2011, which showcased the potential of a team so laden with talent. Despite winning SMM 2011, iG continued to struggle through team coordination and organization issues as all four of its main players scrambled for farm and Faith engaged in what was quickly dubbed \"1 protect 4\". While their individual skill and talent were unquestioned, iG was seen as weaker than either DK or LGD due to their inability to play as a focused team, which was reflected with losses in both DotA and Dota 2, despite their quick invitation to the International 2012 which they then proceeded to win. In the months leading up to the International 2012, iG resolved its team issues and defeated DK and LGD convincingly in DotA capturing the G-League 2012 championship."
    val ThunderDescription = "2017\n" +
            "March 12th - The roster is formed with initial members; vanN, SmAsH, Ztok, and mstco.[1]\n" +
            "March 20th - Jeimari is revealed to have joined the team.[2]\n" +
            "May 5th - Jeimari leaves the team.[3]\n" +
            "July 7th - Greedy is revealed to have joined the team.[4]\n" +
            "August 3rd - The roster is released.[5]\n" +
            "2018\n" +
            "January 8th - A new roster is announced; Mikasa, Jeimari, Brats, GianDK and Jerry.[6]\n" +
            "March 23th - GianDK is removed from the roster due to a match fixing scandal.[7]\n" +
            "April 6th - A new roster is announced; Atun, Jeimari, Frank, Scofield and Prada.[8]\n" +
            "April 16th - Iwo joins the team as coach.[9]\n" +
            "August 30th - Frank and manager CEPs are replaced by Sword and The Azathoth as manager.[10]\n" +
            "November 5th - Scofield and Sword leave the team, they are replaced by Frank and Matthew while Benjaz joins the team as coach.[11]\n" +
            "November 14th - Benjaz leaves to join WP Gaming.[12]\n" +
            "December 15th - Jeimari leaves the team due to personal reasons.[13]\n" +
            "2019\n" +
            "April 1st - The part ways with Matthew while LeoStyle- and Scofield join the team.[14]\n" +
            "April 21st - LeoStyle- departs from the team due to health issue while Jeimari joins the team as a stand-in.[15]\n" +
            "June 13th - Atun, Jeimari and Prada leave the team.[16]\n" +
            "July 1st - Scofield leaves to join Infamous.[17]\n" +
            "July 5th - A new roster is announced for upcoming The International 2019 Qualifiers.[18]\n" +
            "November 15th - Faker and Accel are replaced by LeoStyle- and Matthew.[19]\n" +
            "2020\n" +
            "August 12th - Techies Senior joins the team as streamer.[20]\n" +
            "October 31st - The team part ways with Frank.[21]\n" +
            "December 7th - Matthew takes a break until DPC restarts. Slad1n- joins as stand-in.[22]\n" +
            "2021\n" +
            "January 1st - A new roster is revealed; Frank and MoOz join the team.[23]\n" +
            "June 12th - Fear reveals that he is the coach for the team for The International 10.[24]"
    val OGDescription = "Team OG was originally formed under the name (monkey) Business and was comprised of both experienced veterans in n0tail and Fly as well as new and upcoming talents in Miracle-, Cr1t- and MoonMeander. The team achieved their breakthrough during the Frankfurt Major, defeating European powerhouse Team Secret in the grand finals. The team continued to have a strong presence in the European Dota scene, but after a fourth-place finish at The Summit 4, OG's dominance began to wane and ended with a 7-8th place finish in the Shanghai Major. Despite this, the team rebounded with a 3rd place finish at EPICENTER and claimed a second Dota Major Championship title at the Manila Major. The squad proceeded to defeat Natus Vincere at ESL One Frankfurt 2016, winning the tournament and securing their invite to The International 2016.\n" +
            "\n" +
            "OG performed well in the group stage of The International 2016 and finished first in their group. Despite this, the team was unable to maintain their momentum and fell to the loser's bracket against MVP Phoenix. 7ckingmad would later say in his 'Reflections' interview with Duncan \"Thorin\" Shields that they chose to play MVP Phoenix after their 'complete domination' of them at the Manila Major, and that this may have been a mistake. Following this unexpected loss, the team was eliminated by TNC Gaming and finished 9-12th, in what has been referred to as one of the biggest upsets in professional Dota 2.[1] Shortly after their disappointing run, OG announced that MoonMeander would no longer be an active player, and that Cr1t- and Miracle- would be leaving the team. In the same 'Reflections' interview, 7ckingmad claimed that it was a personality conflict within the team that led to the removal of Moonmeander, and that once the team wasn't remaining as 5, it prompted Miracle to consider other offers."
    val NigmaDescription = "2019\n" +
            "November 25th - The team is announced, consisting of members of the former Team Liquid roster: Miracle-, w33, MinD_ContRoL, GH and KuroKy.[1]\n" +
            "2021\n" +
            "April 6th - w33 is moved from the active roster and becomes the 6th player.[3]\n" +
            "April 10th - iLTW joins the team.[4]"

    val AsterDescription = "2018\n" +
            "September 10th - The team and the lineup are announced: Sylar, Dstones, Xxs, BoBoKa and Fenrir.[1]\n" +
            "September 18th - After the performance in the The Kuala Lumpur Major qualifiers, Dstones is confirmed as a permanent member of the roster.[2]\n" +
            "November 2nd - Dstones is benched. He is replaced by loveyouloveme on loan from For The Dream until December 4th, 2018. Q is also added as a coach on a trial basis. [3]\n" +
            "December 2nd - Dstones begins to play for Room310.\n" +
            "December 4th - loveyouloveme is now a regular member after the loan period.\n" +
            "2019\n" +
            "February 11th - Mushi plays in Sli Minor CN Quallifier, replacing loveyouloveme. He registers with the team on February 19th.[4]\n" +
            "March 28th - Sylar and Fenrir become inactive. Q returns as the coach.[5]\n" +
            "April 1st - Hmx from their training squad FC.A and the coach Q play Dota Pit CN OQ as stand-ins.[6]\n" +
            "April 14th - J and ChYuan join on a trial basis. Q becomes the support player. Mikasa joins as the coach.[7]\n" +
            "April 16th - Sylar leaves to join Team Sirius.[8]\n" +
            "May 5th - Fenrir is loaned to Newbee.[9]\n" +
            "May 26th - J becomes inactive while Kamma joins the team on a trial basis.[10]\n" +
            "September 1st - Sccc joins.[11]\n" +
            "September 8th - Fade joins.[12]\n" +
            "September 20th - Fenrir leaves to join Royal Never Give Up.[13]\n" +
            "2020\n" +
            "February 26th - QQQ joins the team as coach, replacing Mikasa who resigned in January.[14]\n" +
            "August 22nd - A new roster is revealed on stream by BurNIng.[15]\n" +
            "August 24th - ChYuan chooses not to continue his career in China, becomes inactive with the contract being reserved and frozen.[16]\n" +
            "August 26th - Monet and DD斩首 join the team.[17]\n" +
            "September 1st - Sccc is released from the team.[18]\n" +
            "September 16th - J leaves to join Sparking Arrow Gaming.[19]\n" +
            "October 22nd - The roster is announced; 天命 goes inactive while Ch joins the team on a trial basis.[20]\n" +
            "November 7th - Fade is transferred to EHOME.[21]\n" +
            "November 11th - The team part ways with Ch, coach LaNm will stand-in.[22]\n" +
            "2021\n" +
            "April 10th - ChYuan leaves to join Fnatic.[23]"
    val AllianceDescription = "The foundation of what would later become the Alliance Dota 2 team was laid when Swedish DotA veteran Loda, who had just left Singaporean Team Zenith after their dissolution following The International 2012, was approached by a sponsor (which would later become the Alliance organization) asking him if he was interested in putting together a team.[1] Looking back at the glory days of his early career, his decision was to try to go with an all-swedish lineup in the same spirit as his oldest and most successful team, SK Gaming of the 2008 era. He and fellow Swedish support veteran Akke's, eyes fell upon rising Swedish solo-mid star s4, whom Loda had noticed during their HoN days. s4 and AdmiralBulldog were playing for the new upstart team No Tidehunter created by s4 and Canadian support player EternaLEnVy. In late October 2012, it was announced that Loda and Akke had joined team No Tidehunter,[2] only one month before Dreamhack Winter 2012 which the team had qualified for with a mixed roster including German carry Black^.\n" +
            "\n" +
            "Winning the DreamHack Winter tournament in such short time after the Swedish veteran duo's inclusion surprised many and established the team as one of the best teams in the west. During the finals, in which they were trailing 0-1, they managed to bait the entire EG squad into checking the Roshan-pit with an ingenious suicide by AdmiralBulldogs Natures Prophet, and subsequently getting the first blood and eventually turning the finals in front of the home crowd.[3] Alliance did not exist as an organization as of yet, but the team confirmed during the event that they were under contract by an unknown organization and that all the players had their trip to Jonköping paid for, including current captain EternaLEnVy who was flown in all the way from Canada."
    val SecretDescription = "After Natus Vincere and Fnatic both underperformed at The International 2014, two key members of the two organizations, Kuroky and N0tail, respectively, had an idea for a team that was run by the players, not beholden to any esports organization. Kuroky brought on his friend and teammate on Na'Vi, Puppey, while N0tail brought on his friend and teammate, Fly. They rounded out their roster with Alliance midlaner s4, whose team similarly underperformed at TI4. The roster made their public debut in the qualifiers for Star Ladder Star Series Season 10."
    val liquidDescription = "Team Liquid would come into The International 2017 as one of the favorites. For the Group Stage, they would be seeded into Group A alongside other such favorites as Evil Geniuses, LGD Gaming, and Team Secret amongst others. After a strong start to the Group Stage, Liquid found themselves in a neck-and-neck race with LGD Gaming for the top seed of their group, which Team Liquid finally were able to secure with an overall score of 13-3. This meant that they would be allowed to pick their opponent in the Upper Bracket of the Main Event from the 3rd and 4th placed teams from Group B: Virtus.pro or Invictus Gaming. Unwilling to face the aggressive Russian squad, Team Liquid chose iG as their first opponent.\n" +
            "\n" +
            "However, the first series of the main event did not go as planned and Team Liquid dropped down to the Lower Bracket after losing 1-2 to iG. To make it to the Grand Finals, they would have to make a run similar to Digital Chaos's run at The International 2016. Their first opponent in the Lower Bracket would be Team Secret, to whom they lost the first game of the series. Team Liquid found themselves one game away from elimination, but not for the last time at this event. Beating out the surprise contender Team Empire, fellow favorites Virtus.pro and LGD Gaming, Team Liquid managed to reach the Lower Bracket final, where they faced another surprise contender in LGD.Forever Young. LFY had managed to nearly sweep Group B, after only dropping two games and hadn't dropped a game on the main stage until the Upper Bracket Final against Newbee. LFY quickly proved themselves a formidable opponent and after the first game of the Lower Bracket final, Team Liquid found themselves once again with their backs against the wall. However, they prevailed yet again and turned the series around on the back of MinD_ContRoL's Nature's Prophet. Team Liquid had reached the Grand Final, where Newbee waited. Team Liquid had never dropped a series to Newbee and this time would be no different: Liquid swept the series 3-0 in dominant fashion, claiming their first Dota Major Championship and becoming the seventh winner of The International[3] and over 10 million USD in prize money.\n" +
            "\n" +
            "This would be the first time that a TI Grand Final would end in a 3-0 sweep as well as the first time a team made up of 5 different nationalities would win the Aegis. Newbee's Faith, who was part of the Invictus Gaming roster that won The International 2012, was also denied his second TI win. Liquid's victory also continued the tradition of the TI winner alternating between Chinese and Western teams."
    val VikingDescription = "Vikin.gg formed in 2019. In November of that year, the roster of Shad, Meepor, Tobi, Aramis and Seleri was signed, with the team finishing runners-up in the Bukovel Minor 2020 qualifiers.\n" +
            "\n" +
            "After BOOM joined the team, Vikin.gg secured a number of impressive tournament results, winning a total of 10 tournaments in 2020 and gradually earning recognition as a tier 1 team. The notable accomplishments included winning the European divisions of BTS Pro Series 3 and The Summit 13."
}