package com.example.dota2project.UI.Matches

import com.example.dota2project.MatchPlayerModel

data class MatchInfo(
    val barracks_status_dire: Int,
    val barracks_status_radiant: Int,
    val chat: Any,
    val cluster: Int,
    val cosmetics: Any,
    val dire_score: Int,
    val dire_team_id: Int,
    val draft_timings: Any,
    val duration: Int,
    val engine: Int,
    val first_blood_time: Int,
    val game_mode: Int,
    val human_players: Int,
    val leagueid: Int,
    val lobby_type: Int,
    val match_id: Long,
    val match_seq_num: Long,
    val negative_votes: Int,
    val objectives: Any,
    val patch: Int,
    val players: List<MatchPlayerModel>,
    val positive_votes: Int,
    val radiant_gold_adv: Any,
    val radiant_score: Int,
    val radiant_team_id: Int,
    val radiant_win: Boolean,
    val radiant_xp_adv: Any,
    val region: Int,
    val replay_salt: Int,
    val replay_url: String,
    val series_id: Int,
    val series_type: Int,
    val skill: Int,
    val start_time: Int,
    val teamfights: Any,
    val tower_status_dire: Int,
    val tower_status_radiant: Int,
    val version: Any,
) {
}